debug = false

defaultEntryPoints = ["https","http"]

# The syntax is somewhat esoteric IMHO so this is mostly copy-paste
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
# Put here your main domain name
domain = "my-own-domain.com"
watch = true
exposedbydefault = false

[acme]
# Put here your mail adress in order to be informed by a bot when you will need to ask for a new SSL certificate
email = "your@address.com"
storage = "acme.json"
entryPoint = "https"
OnHostRule = true
# Uncomment this if you want to test your domain against ACME staging environment  
# caServer = "https://acme-staging.api.letsencrypt.org/directory"
[acme.httpChallenge]
entryPoint = "http"

# Enable web configuration backend
[web]

# Web administration port, proxied in docker-compose.yml
address = ":8080"
